apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: tomcat-app
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32080
